services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  data-migration-job:
    build: .
    container_name: romanowalex/data-migration-job:v1.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SOURCE_DATABASE_CONNECTION_URL: jdbc:postgresql://postgres:5432/source
      SOURCE_DATABASE_USER: program
      SOURCE_DATABASE_PASSWORD: test
      TARGET_DATABASE_CONNECTION_URL: jdbc:postgresql://postgres:5432/target
      TARGET_DATABASE_USER: program
      TARGET_DATABASE_PASSWORD: test
    volumes:
      - ./external.yml:/opt/config/external.yml
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres:
